FROM python:3

WORKDIR /python

COPY requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 8001

COPY . /python

CMD [ "python", "main.py" ]
# docker build -t sorted_algoritm .
# docker run -it -e DISPLAY=$DISPLAY --name sorted_container sorted_algoritm